### ISSUE TITLE
Spurious fp16 MobileBERT model size

### ISSUE THREAD

**Issue by sayakpaul** [sayakpaul/BERT-for-Mobile#3]
@khanhlvg

For benchmarking and comparison purposes, I used the [Text classification with TensorFlow Lite Model Maker](https://www.tensorflow.org/lite/tutorials/model_maker_text_classification) example and exported the trained model with `float16` quantization in the following way - 

```python
config = configs.QuantizationConfig.create_float16_quantization(optimizations=[tf.lite.Optimize.DEFAULT])
config._experimental_new_quantizer = True

model.export(export_dir='mobilebert_fp16/', tflite_filename="mobilebert_sst_2_fp16.tflite",
             quantization_config=config)
```

To my wonder, the resultant TFLite model is of the same size as the dynamic-range quantized model. Is this expected? Here's the [Colab Notebook](https://colab.research.google.com/gist/sayakpaul/0f166f6b5bfd35231e3f7c0237fabd62/model_maker_text_classification.ipynb) for reproducibility.

**Comment by ziyeqinghan** [comment]
We have fixed the bug in the [commit](https://github.com/tensorflow/examples/commit/71e2dfa2afd0e81fee7a1157984954ad2e7d6171). You can install [`tflite-model-maker-nightly`](https://pypi.org/project/tflite-model-maker-nightly/) instead of `tflite-model-maker` once nightly release a new version tomorrow. Please try whether it works for the new nightly version.

**Comment by sayakpaul** [comment]
Thanks @ziyeqinghan. Will try it tomorrow and report here 💯

**Comment by sayakpaul** [comment]
@ziyeqinghan the latest nightly worked.
